import math

SCREEN_WIDTH = 768
SCREEN_HEIGHT = 768

SIZE_X = 64
SIZE_Y = 64

SIDE_LENGTH = math.floor(min(SCREEN_WIDTH/SIZE_X ,SCREEN_HEIGHT/SIZE_Y))

VECTOR_LENGTH = 1

ENTROPY = 3.6

#log (chunk_size/min_chunk_size, scale) = int
CHUNK_SIZE = 32
MIN_CHUNK_SIZE = 1
SCALE = 2

ROUGHNESS = 2

NUM_PLAYERS = 8

# 0 TO 1
DRAGON_SPAWN_RATE = 0.2
DRAGON_SEPARATION = 21

RUNE_SPAWN_RATE = 0.0036

OASIS_SPAWN_RATE = 0.025
OASIS_SEPARATION = 11

MINESHAFT_SPAWN_RATE = 0.005
MINESHAFT_SEPARATION = 11

FRUIT_TREE_SPAWN_RATE = 0.005
FRUIT_TREE_SEPARATION = 3

COCONUT_CANOPY_SPAWN_RATE = 0.01
COCONUT_CANOPY_SEPARATION = 3

SHARK_SPAWN_RATE = 0.005
SHARK_SEPARATION = 7

# HEIGHT DISTRIBUTION
ABYSS = 0.125
DEEP_SEA = 0.25
SHALLOW_SEA = 0.35
BEACH = 0.45
GRASSLAND = 0.65
DESERT = 0.75
BADLANDS = 0.875
LAVA = 1